language: generic
dist: xenial
services: docker

cache:
  directories:
  - $HOME/.ccache
  - $HOME/.cache/pip

env:
  global:
  - REPO_DIR="pygeos"
  - BUILD_COMMIT=0.6
  - PLAT=x86_64
  - UNICODE_WIDTH=32
  - USE_CCACHE=1

matrix:
  include:
  - name: "Python 3.5 x86_64 linux"
    os: linux
    env:
    - MB_PYTHON_VERSION=3.5
    - NP_BUILD_DEP=numpy==1.10.4
  - name: "Python 3.6 x86_64 linux"
    os: linux
    env:
    - MB_PYTHON_VERSION=3.6
    - NP_BUILD_DEP=numpy==1.11.3
  - name: "Python 3.7 x86_64 linux"
    os: linux
    env:
    - MB_PYTHON_VERSION=3.7
    - NP_BUILD_DEP=numpy==1.14.5
  - name: "Python 3.8 x86_64 linux"
    os: linux
    env:
    - MB_PYTHON_VERSION=3.8
    - NP_BUILD_DEP=numpy==1.17.3
  - name: "Python 3.5 osx"
    os: osx
    env:
    - MB_PYTHON_VERSION=3.5
    - NP_BUILD_DEP=numpy==1.10.4
  - name: "Python 3.6 osx"
    os: osx
    env:
    - MB_PYTHON_VERSION=3.6
    - NP_BUILD_DEP=numpy==1.11.3
  - name: "Python 3.7 osx"
    os: osx
    env:
    - MB_PYTHON_VERSION=3.7
    - NP_BUILD_DEP=numpy==1.14.5
  - os: osx
    osx_image: xcode10.1
    env:
    - MB_PYTHON_VERSION=3.8
    - NP_BUILD_DEP=numpy==1.17.3
    - NP_TEST_DEP=numpy==1.17.3
    - MB_PYTHON_OSX_VER=10.9

before_install:
    - python -c "import fcntl; fcntl.fcntl(1, fcntl.F_SETFL, 0)"
    - BUILD_DEPENDS="$NP_BUILD_DEP"
    - TEST_DEPENDS="$NP_BUILD_DEP pytest"
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - before_install

install:
    - clean_code $REPO_DIR $BUILD_COMMIT
    - build_wheel $REPO_DIR $PLAT

script:
    - install_run $PLAT
